namespace :season_data do

  desc 'create application task rates'
  task :teams => :environment do
    teams=[
        {
            team: 'SMS PZPS Spała II',
            logo: 'sms.jpg'
        },
        {
            team: 'Eco-Team AZS IV LO Częstochowa',
            logo: 'czestochowa.jpg'
        },
        {
            team: 'LUKS Wilki Wilczyn',
            logo: 'wilczyn.jpg'
        },
        {
            team: 'Tubądzin Volley MOSiR Sieradz',
            logo: 'sieradz_logo.jpg'
        },
        {
            team: 'WKRĘT-MET LKPS Borowno',
            logo: 'borowno.jpeg'
        },
        {
            team: 'LUMKS Kasztelan Rozprza',
            logo: 'kasztelan.png'
        },
        {
            team: 'SPS Konspol Słupca',
            logo: 'slupca.jpeg'
        },
        {
            team: 'MKS Bzura Ozorków',
            logo: 'bzura.jpeg'
        },
        {
            team: 'LKS Czarni Rząśnia',
            logo: 'rzasnia.jpg'
        },
        {
            team: 'PGE Skra II Bełchatów',
            logo: 'skra.png'
        }
    ]
    teams.each do |t|
      image = Image.new
      image.image = Rails.root.join('public', t[:logo]).open
      image.save!
      o = Team.create!( name: t[:team], my_team: t[:team] == 'LUMKS Kasztelan Rozprza', image: image )
    end
  end

  task :clear => :environment do
    Match.destroy_all
    MatchType.destroy_all
    Team.destroy_all
  end

  task :match => :environment do
    season = MatchType.create!(name: 'II Liga', full_name: 'II Liga Mężczyzn 2018/2019')
    matches=[
        { number: 1,
          home: 'SMS PZPS Spała II',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 46,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'SMS PZPS Spała II'},
        { number: 2,
          home: 'LUKS Wilki Wilczyn',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
        { number: 47,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 3,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 48,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 4,
          home: 'SPS Konspol Słupca',
          guest: 'MKS Bzura Ozorków'},
        { number: 49,
          home: 'MKS Bzura Ozorków',
          guest: 'SPS Konspol Słupca'},
        { number: 5,
          home: 'LKS Czarni Rząśnia',
          guest: 'PGE Skra II Bełchatów'},
        { number: 50,
          home: 'PGE Skra II Bełchatów',
          guest: 'LKS Czarni Rząśnia'},
        { number: 6,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'PGE Skra II Bełchatów'},
        { number: 51,
          home: 'PGE Skra II Bełchatów',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 7,
          home: 'MKS Bzura Ozorków',
          guest: 'LKS Czarni Rząśnia'},
        { number: 52,
          home: 'LKS Czarni Rząśnia',
          guest: 'MKS Bzura Ozorków'},
        { number: 8,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'SPS Konspol Słupca'},
        { number: 53,
          home: 'SPS Konspol Słupca',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 9,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 54,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
        { number: 10,
          home: 'SMS PZPS Spała II',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 55,
          home: 'LUKS Wilki Wilczyn',
          guest: 'SMS PZPS Spała II'},
        { number: 11,
          home: 'LUKS Wilki Wilczyn',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 56,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 12,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'SMS PZPS Spała II'},
        { number: 57,
          home: 'SMS PZPS Spała II',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 13,
          home: 'SPS Konspol Słupca',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
        { number: 58,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'SPS Konspol Słupca'},
        { number: 14,
          home: 'LKS Czarni Rząśnia',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 59,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'LKS Czarni Rząśnia'},
        { number: 15,
          home: 'PGE Skra II Bełchatów',
          guest: 'MKS Bzura Ozorków'},
        { number: 60,
          home: 'MKS Bzura Ozorków',
          guest: 'PGE Skra II Bełchatów'},
        { number: 16,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'MKS Bzura Ozorków'},
        { number: 61,
          home: 'MKS Bzura Ozorków',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 17,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'PGE Skra II Bełchatów'},
        { number: 62,
          home: 'PGE Skra II Bełchatów',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 18,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'LKS Czarni Rząśnia'},
        { number: 63,
          home: 'LKS Czarni Rząśnia',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
        { number: 19,
          home: 'SMS PZPS Spała II',
          guest: 'SPS Konspol Słupca'},
        { number: 64,
          home: 'SPS Konspol Słupca',
          guest: 'SMS PZPS Spała II'},
        { number: 20,
          home: 'LUKS Wilki Wilczyn',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 65,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 21,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 66,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 22,
          home: 'SPS Konspol Słupca',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 67,
          home: 'LUKS Wilki Wilczyn',
          guest: 'SPS Konspol Słupca'},
        { number: 23,
          home: 'LKS Czarni Rząśnia',
          guest: 'SMS PZPS Spała II'},
        { number: 68,
          home: 'SMS PZPS Spała II',
          guest: 'LKS Czarni Rząśnia'},
        { number: 24,
          home: 'PGE Skra II Bełchatów',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
        { number: 69,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'PGE Skra II Bełchatów'},
        { number: 25,
          home: 'MKS Bzura Ozorków',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 70,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'MKS Bzura Ozorków'},
        { number: 26,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 71,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 27,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'MKS Bzura Ozorków'},
        { number: 72,
          home: 'MKS Bzura Ozorków',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
        { number: 28,
          home: 'SMS PZPS Spała II',
          guest: 'PGE Skra II Bełchatów'},
        { number: 73,
          home: 'PGE Skra II Bełchatów',
          guest: 'SMS PZPS Spała II'},
        { number: 29,
          home: 'LUKS Wilki Wilczyn',
          guest: 'LKS Czarni Rząśnia'},
        { number: 74,
          home: 'LKS Czarni Rząśnia',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 30,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'SPS Konspol Słupca'},
        { number: 75,
          home: 'SPS Konspol Słupca',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 31,
          home: 'SPS Konspol Słupca',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 76,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'SPS Konspol Słupca'},
        { number: 32,
          home: 'LKS Czarni Rząśnia',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 77,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'LKS Czarni Rząśnia'},
        { number: 33,
          home: 'PGE Skra II Bełchatów',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 78,
          home: 'LUKS Wilki Wilczyn',
          guest: 'PGE Skra II Bełchatów'},
        { number: 34,
          home: 'MKS Bzura Ozorków',
          guest: 'SMS PZPS Spała II'},
        { number: 79,
          home: 'SMS PZPS Spała II',
          guest: 'MKS Bzura Ozorków'},
        { number: 35,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
        { number: 80,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 36,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
        { number: 81,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 37,
          home: 'SMS PZPS Spała II',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 82,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'SMS PZPS Spała II'},
        { number: 38,
          home: 'LUKS Wilki Wilczyn',
          guest: 'MKS Bzura Ozorków'},
        { number: 83,
          home: 'MKS Bzura Ozorków',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 39,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'PGE Skra II Bełchatów'},
        { number: 84,
          home: 'PGE Skra II Bełchatów',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 40,
          home: 'SPS Konspol Słupca',
          guest: 'LKS Czarni Rząśnia'},
        { number: 85,
          home: 'LKS Czarni Rząśnia',
          guest: 'SPS Konspol Słupca'},
        { number: 41,
          home: 'LKS Czarni Rząśnia',
          guest: 'Eco-Team AZS IV LO Częstochowa'},
        { number: 86,
          home: 'Eco-Team AZS IV LO Częstochowa',
          guest: 'LKS Czarni Rząśnia'},
        { number: 42,
          home: 'PGE Skra II Bełchatów',
          guest: 'SPS Konspol Słupca'},
        { number: 87,
          home: 'SPS Konspol Słupca',
          guest: 'PGE Skra II Bełchatów'},
        { number: 43,
          home: 'MKS Bzura Ozorków',
          guest: 'WKRĘT-MET LKPS Borowno'},
        { number: 88,
          home: 'WKRĘT-MET LKPS Borowno',
          guest: 'MKS Bzura Ozorków'},
        { number: 44,
          home: 'LUMKS Kasztelan Rozprza',
          guest: 'LUKS Wilki Wilczyn'},
        { number: 89,
          home: 'LUKS Wilki Wilczyn',
          guest: 'LUMKS Kasztelan Rozprza'},
        { number: 45,
          home: 'Tubądzin Volley MOSiR Sieradz',
          guest: 'SMS PZPS Spała II'},
        { number: 90,
          home: 'SMS PZPS Spała II',
          guest: 'Tubądzin Volley MOSiR Sieradz'},
    ]
    dates=[
        Date.new(2018,11,10),
        Date.new(2019,01,19),
        Date.new(2018,11,24),
        Date.new(2019,2,2),
        Date.new(2018,11,17),
        Date.new(2019,1,26),
        Date.new(2018,9,29),
        Date.new(2018,12,1),
        Date.new(2018,10,6),
        Date.new(2018,12,8),
        Date.new(2018,10,13),
        Date.new(2018,12,15),
        Date.new(2018,10,20),
        Date.new(2018,12,22),
        Date.new(2018,10,27),
        Date.new(2019,1,5),
        Date.new(2018,11,7),
        Date.new(2019,1,12),
    ].sort

    matches.each do |m|
      round = (m[:number].to_f/5).ceil
      home =  Team.find_by(name: m[:home])
      guest =  Team.find_by(name: m[:guest])
      date = dates[round-1]
      Match.create!(round: round, home: home, guest: guest, match_date: date, match_type: season)
    end
  end
end
